// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { Providers } from './providers'
import "./globals.css";
import type { Metadata } from "next";
import { Flex, Spacer, Stack } from '@chakra-ui/react';
import { Inter } from 'next/font/google';
export const metadata: Metadata = {
  title: "Welcome to We All Code",
};


const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Flex flexDirection={'row'} alignItems={'center'} minH={'100%'} justifyContent={'center'} p={6}>
            <Stack alignItems={'center'} maxW={'container.lg'} spacing={10} className={inter.className} textAlign={'center'}>
              {children}
            </Stack>
          </Flex>
        </Providers>
      </body>
    </html>
  )
}